---
title: "LFMM then PCA"
output: html_notebook
---

Open the data

```{r}
source('../R/lfmm.R')
source('../R/spectral_fst.R')
```


```{r}
genotype_athaliana <- read.lfmm('../data/athaliana_n241_L10k.lfmm')
env_var <- read.env('../data/climate.txt')
```

```{r}
pop_athaliana <- read.table('../data/pop_label.txt')[,1]
```

We now want to obtain PCA axis for A thaliana without adjustment
```{r}
spectral_athaliana <- compute_partition(genotype_athaliana, pop_athaliana)
wright_fst_athaliana <- mean_wright_fst(genotype_athaliana, pop_athaliana)
```

```{r}
print("mean Fst compute with wright formula :")
wright_fst_athaliana
print("Fst compute with between population matrix Zst")
spectral_athaliana$Fst
print("Fst estimation using Z matrix")
spectral_athaliana$Fst_estimate
```

We now run LFMM

```{r}
lfmm_athaliana <- lfmm2(genotype_athaliana, env_var, 222)

```

```{r}
adjusted_genotype <- lfmm_athaliana@U %*% t(lfmm_athaliana@V)
```

```{r}
spectral_adjusted_athaliana <- compute_partition(adjusted_genotype, pop_athaliana)
```

```{r}
print("Fst compute with between population matrix Zst")
spectral_adjusted_athaliana$Fst
print("Fst estimation using Z matrix")
spectral_adjusted_athaliana$Fst_estimate
```

We now plot our graphs

```{r}
m <- cbind(spectral_athaliana$eigenZ[1:6],spectral_adjusted_athaliana$eigenZ[1:6])
plot(seq(1,12)/2,as.numeric(t(m)), 
     col = rep(c("darkblue","orange"), length = 12), 
     type = "h", lwd = 10, 
     ylab = "Proportion of variance",
     xlab = "PC axis",
    # main = "PCA",
     cex.axis = .9,
     las = 1)

legend(x = 3.5, y = 0.081, 
       legend = c("All SNPs", "Adjusted data"),
       col = c("darkblue","orange"),
       lty = c(1,1),
       pch = 19,
       cex = 1)
```

```{r}
m <- cbind(c(spectral_athaliana$eigenZst[1], spectral_athaliana$eigenZs[1:5]),
           c(spectral_adjusted_athaliana$eigenZst[1], spectral_adjusted_athaliana$eigenZs[1:5]))
plot(seq(1,12)/2,as.numeric(t(m)), 
     col = rep(c("lightblue","orange"), length = 12), 
     type = "h", lwd = 10, 
     ylab = "Proportion of variance",
     xlab = "PC axis",
    # main = "Structure Components",
     cex.axis = .9,
     las = 1)

legend(x = 3.5, y = 0.077, 
       legend = c("All SNPs", "Adjusted data"),
       col = c("lightblue","orange"),
       lty = c(1,1),
       pch = 19,
       cex = 1)
```

Computing Fst using new formula

```{r}
Z_athaliana <- scale(genotype_athaliana)
s_athaliana <- summary(lm(Z_athaliana~ as.factor(pop_athaliana)))
f_athaliana <- sapply(s_athaliana, FUN=function(smr) smr$r.squared)
mean(f_athaliana)
```

We obtain the same results. Let's check with adjusted genotype

```{r}
Z_adjusted <- scale(adjusted_genotype)
s_adjusted<- summary(lm(Z_adjusted~ as.factor(pop_athaliana)))
f_adjusted <- sapply(s_adjusted, FUN=function(smr) smr$r.squared)
mean(f_adjusted)
```

The new formula is working properly

